### ISSUE TITLE
Alternate row color

### ISSUE THREAD

**Issue by 0xCoto** [HeRTA/FRBSTATS#18]
Slight row color alternations helps navigate through the data more conveniently.

Something like this could work:
```css
table.dataTable td.sorting_1 { background-color: white; border:1px lightgrey; }
table.dataTable td { background-color: white;  border:1px lightgrey; }
table.dataTable tr.odd { background-color: white;  border:1px lightgrey; }
table.dataTable tr.even { background-color: white; border:1px lightgrey; }
```
